<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Interfaces\IBuilders\**" />
    <EmbeddedResource Remove="Interfaces\IBuilders\**" />
    <None Remove="Interfaces\IBuilders\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="12.0.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.27" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.27" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.27">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Khyata.Domain\Khyata.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Mappings\" />
  </ItemGroup>

</Project>
